title: frantic.im
author: Alex Kotliarskyi
permalink: :title
email: contact@frantic.im
twitter: https://twitter.com/alex_frantic
description: Occasional posts on technology and stuff
baseurl: ""
url: https://frantic.im
markdown: kramdown
highlighter: rouge
exclude:
  - "*.sketch"
  - "vendor"
data:
  menu:
    - name: Blog
      link: /blog/
    - name: Talks
      link: /talks/
    - name: Projects
      link: /projects/
    - name: About
      link: /about/
