#!/bin/bash

set -o allexport
source .env set
set +o allexport

mkdir -p _build
rm -rf _build/*
cp favicon.png _build/
cp CNAME _build/
cp -r fonts _build/
./scripts/og-image.js --all
cp -r assets _build/
cp -r figma _build/
./scripts/make.js "$*"
