#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'

root = File.join(__dir__, '..')
name = Time.now.to_s.split(' ')[0..1].join('-').gsub(':', '.') + '.md'
path = File.join(root, '_drafts', name)
template = File.join(root, '.post-template')

FileUtils.cp(template, path)
system 'code', path
